"""Build the 5-dataset main-matrix headline table (§3.3 + §5).

Reads per_cell.csv files for tallyqa, chartqa, mathvista (E5e) and plotqa,
infographicvqa (E7) and emits two artifacts:

  docs/insights/_data/main_panel_5dataset_per_cell.csv
    long format: model × dataset × {a-arm, m-arm} × {adopt, df, em}
  docs/insights/_data/main_panel_5dataset_summary.md
    markdown table for paper headline (3 models × 5 datasets, S1
    wrong-base; columns adopt(a)/adopt(m)/df(a)/df(m)/em(a)/em(m)).

Wrong-base S1 cells only (cond_class in {a,m}, stratum='S1',
base_correct=False) — paper canonical per references/project.md §0.4.3.

Usage:
  uv run python scripts/build_e5e_e7_5dataset_summary.py
  uv run python scripts/build_e5e_e7_5dataset_summary.py --print
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "docs" / "insights" / "_data"

DATASET_SOURCES = [
    ("TallyQA",         "experiment_e5e_tallyqa_full"),
    ("ChartQA",         "experiment_e5e_chartqa_full"),
    ("MathVista",       "experiment_e5e_mathvista_full"),
    ("PlotQA",          "experiment_e7_plotqa_full"),
    ("InfographicVQA",  "experiment_e7_infographicvqa_full"),
]
MODEL_DISPLAY = {
    "llava-next-interleaved-7b": "llava-interleave-7b",
    "qwen2.5-vl-7b-instruct":    "qwen2.5-vl-7b",
    "gemma3-27b-it":             "gemma3-27b",
}
MODEL_ORDER = list(MODEL_DISPLAY)


def _load_per_cell(exp_dir: str) -> pd.DataFrame | None:
    p = DATA_DIR / f"{exp_dir}_per_cell.csv"
    if not p.exists():
        print(f"[warn] {p.name} missing; run analyze_e5e_wrong_correct.py --exp-dir {exp_dir}")
        return None
    return pd.read_csv(p)


def _pick_canonical_run(df: pd.DataFrame) -> pd.DataFrame:
    """For each model, keep rows from the run with the largest total n.

    Phase A scripts: pick largest run, not alphabetically-latest.
    """
    keep_runs: dict[str, str] = {}
    for model, sub in df.groupby("model", sort=False):
        # Sum n across all (cond, stratum, base_correct) rows per run; pick max.
        per_run_totals = sub.groupby("run")["n"].sum().sort_values()
        keep_runs[model] = per_run_totals.index[-1]
    mask = df.apply(lambda r: r["run"] == keep_runs.get(r["model"]), axis=1)
    return df[mask].copy()


def _wrong_base_s1(df: pd.DataFrame) -> pd.DataFrame:
    return df[
        (df["stratum"] == "S1")
        & (df["base_correct"] == False)
        & (df["cond_class"].isin(["a", "m"]))
    ].copy()


def build_long_table() -> pd.DataFrame:
    rows: list[dict] = []
    for ds_name, exp_dir in DATASET_SOURCES:
        df = _load_per_cell(exp_dir)
        if df is None or df.empty:
            continue
        df = _pick_canonical_run(df)
        df = _wrong_base_s1(df)
        for _, r in df.iterrows():
            rows.append({
                "dataset":      ds_name,
                "exp_dir":      exp_dir,
                "model":        r["model"],
                "run":          r["run"],
                "cond_class":   r["cond_class"],
                "n":            int(r["n"]),
                "n_pb_ne_anchor": int(r.get("n_pb_ne_anchor") or 0),
                "n_numeric_anchor": int(r.get("n_numeric_anchor") or 0),
                "adopt_M2":     float(r["adopt_M2"]),
                "direction_follow_M2": float(r["direction_follow_M2"]),
                "exact_match":  float(r["exact_match"]),
            })
    long_df = pd.DataFrame(rows)
    return long_df


def build_summary_md(long_df: pd.DataFrame) -> str:
    pieces: list[str] = []
    pieces.append("# 5-dataset main-matrix headline (S1 wrong-base, C-form)")
    pieces.append("")
    pieces.append("Auto-generated by `scripts/build_e5e_e7_5dataset_summary.py`.")
    pieces.append("Per-cell source: `docs/insights/_data/{exp}_per_cell.csv`.")
    pieces.append("")
    pieces.append("| dataset | model | n | adopt(a) | df(a) | adopt(m) | df(m) | em(a) | em(m) |")
    pieces.append("|---|---|---:|---:|---:|---:|---:|---:|---:|")
    for ds_name, _ in DATASET_SOURCES:
        sub = long_df[long_df["dataset"] == ds_name]
        if sub.empty:
            continue
        for model in MODEL_ORDER:
            ms = sub[sub["model"] == model]
            if ms.empty:
                continue
            a = ms[ms["cond_class"] == "a"].iloc[0] if not ms[ms["cond_class"] == "a"].empty else None
            m = ms[ms["cond_class"] == "m"].iloc[0] if not ms[ms["cond_class"] == "m"].empty else None
            n = int(a["n"]) if a is not None else (int(m["n"]) if m is not None else 0)
            adopt_a = f"{a['adopt_M2']:.3f}" if a is not None else "—"
            df_a    = f"{a['direction_follow_M2']:.3f}" if a is not None else "—"
            em_a    = f"{a['exact_match']:.3f}" if a is not None else "—"
            adopt_m = f"{m['adopt_M2']:.3f}" if m is not None else "—"
            df_m    = f"{m['direction_follow_M2']:.3f}" if m is not None else "—"
            em_m    = f"{m['exact_match']:.3f}" if m is not None else "—"
            pieces.append(f"| {ds_name} | {MODEL_DISPLAY[model]} | {n} | "
                          f"{adopt_a} | {df_a} | {adopt_m} | {df_m} | {em_a} | {em_m} |")
        pieces.append("")
    return "\n".join(pieces)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--print", action="store_true",
                    help="Print the markdown summary to stdout in addition to writing.")
    ap.add_argument("--out-csv",
                    default=str(DATA_DIR / "main_panel_5dataset_per_cell.csv"))
    ap.add_argument("--out-md",
                    default=str(DATA_DIR / "main_panel_5dataset_summary.md"))
    args = ap.parse_args()

    long_df = build_long_table()
    if long_df.empty:
        print("[err] no rows produced — check that per_cell.csv files exist for all 5 datasets")
        sys.exit(1)
    long_df.to_csv(args.out_csv, index=False)
    print(f"[wrote] {args.out_csv} ({len(long_df)} rows)")

    md = build_summary_md(long_df)
    Path(args.out_md).write_text(md, encoding="utf-8")
    print(f"[wrote] {args.out_md}")

    if args.print:
        print()
        print(md)


if __name__ == "__main__":
    main()
