"""Aggregate E5b 5-stratum cross-dataset decay into a single summary table.

Reads `docs/insights/_data/experiment_e5b_5strat_<ds>_onevision_per_cell.csv`
for the 4 cross-datasets that previously had only S1, and emits the
canonical per-stratum decay table for §5 plausibility-window validation.

Wrong-base slice (`base_correct=False`): the audience for anchor pull —
samples where the model is uncertain to begin with.

Output:
- `docs/insights/_data/e5b_5strat_decay_per_dataset.csv`
- `docs/insights/_data/e5b_5strat_decay_per_dataset.md`
"""

from __future__ import annotations

import csv
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "docs" / "insights" / "_data"

DATASETS = [
    ("MathVista", "mathvista"),
    ("ChartQA", "chartqa"),
    ("InfoVQA", "infographicvqa"),
    ("PlotQA", "plotqa"),
]
STRATA = ["S1", "S2", "S3", "S4", "S5"]


def _load_per_cell(ds_slug: str) -> list[dict[str, str]]:
    path = DATA_DIR / f"experiment_e5b_5strat_{ds_slug}_onevision_per_cell.csv"
    with path.open() as f:
        return list(csv.DictReader(f))


def _row(rows: list[dict[str, str]], cond: str, stratum: str, base_correct: bool) -> dict[str, str]:
    flag = "True" if base_correct else "False"
    for r in rows:
        if r["cond_class"] == cond and r["stratum"] == stratum and r["base_correct"] == flag:
            return r
    raise KeyError(f"missing row cond={cond} stratum={stratum} base_correct={flag}")


def _decay_block(rows: list[dict[str, str]], arm: str, base_correct: bool) -> dict[str, dict[str, float]]:
    out: dict[str, dict[str, float]] = {}
    for s in STRATA:
        r = _row(rows, arm, s, base_correct)
        out[s] = {
            "n": float(r["n"]),
            "adopt": float(r["adopt_M2"]),
            "df": float(r["direction_follow_M2"]),
            "em": float(r["exact_match"]),
        }
    return out


def _d_arm(rows: list[dict[str, str]], base_correct: bool) -> dict[str, float]:
    r = _row(rows, "d", "S0", base_correct)
    return {"n": float(r["n"]), "em": float(r["exact_match"])}


def main() -> None:
    csv_path = DATA_DIR / "e5b_5strat_decay_per_dataset.csv"
    md_path = DATA_DIR / "e5b_5strat_decay_per_dataset.md"

    csv_rows: list[dict[str, str | float]] = []
    md_blocks: list[str] = []

    for label, slug in DATASETS:
        rows = _load_per_cell(slug)
        a_wrong = _decay_block(rows, "a", base_correct=False)
        m_wrong = _decay_block(rows, "m", base_correct=False)
        d_wrong = _d_arm(rows, base_correct=False)

        # CSV: long-form, one row per (dataset, arm, stratum)
        for arm_label, block in (("a", a_wrong), ("m", m_wrong)):
            for s in STRATA:
                cell = block[s]
                csv_rows.append({
                    "dataset": label,
                    "arm": arm_label,
                    "stratum": s,
                    "n": int(cell["n"]),
                    "adopt": round(cell["adopt"], 4),
                    "df": round(cell["df"], 4),
                    "em": round(cell["em"], 4),
                })
        csv_rows.append({
            "dataset": label,
            "arm": "d",
            "stratum": "S0",
            "n": int(d_wrong["n"]),
            "adopt": "",
            "df": "",
            "em": round(d_wrong["em"], 4),
        })

        # MD: per-dataset table block
        block_lines: list[str] = []
        block_lines.append(f"### {label} — wrong-base (base_correct=False)")
        block_lines.append("")
        block_lines.append("| arm | n(S1) | metric | S1 | S2 | S3 | S4 | S5 | Δ(S1→S5) |")
        block_lines.append("|---|---|---|---|---|---|---|---|---|")
        for arm_label, block in (("a", a_wrong), ("m", m_wrong)):
            n_s1 = int(block["S1"]["n"])
            for metric in ("adopt", "df", "em"):
                vals = [block[s][metric] for s in STRATA]
                cells = " | ".join(f"{v:.3f}" for v in vals)
                delta = vals[-1] - vals[0]
                block_lines.append(
                    f"| {arm_label} | {n_s1} | {metric} | {cells} | {delta:+.3f} |"
                )
        block_lines.append(f"| d | {int(d_wrong['n'])} | em | — | — | — | — | — | {d_wrong['em']:.3f} (S0) |")
        block_lines.append("")
        md_blocks.append("\n".join(block_lines))

    # Write CSV
    with csv_path.open("w", newline="") as f:
        writer = csv.DictWriter(
            f, fieldnames=["dataset", "arm", "stratum", "n", "adopt", "df", "em"]
        )
        writer.writeheader()
        for row in csv_rows:
            writer.writerow(row)
    print(f"[wrote] {csv_path}")

    # Write MD
    md = []
    md.append("# E5b 5-stratum cross-dataset decay (OneVision Main)")
    md.append("")
    md.append("Generated by `scripts/build_e5b_5strat_decay_summary.py`.")
    md.append("Source: `outputs/experiment_e5b_5strat_<ds>_onevision/llava-onevision-qwen2-7b-ov/<ts>/predictions.jsonl`")
    md.append("via `analyze_e5e_wrong_correct.py` per-cell aggregator.")
    md.append("")
    md.append("Wrong-base slice only (the audience for anchor pull).")
    md.append("")
    md.append("Δ(S1→S5) interpretation:")
    md.append("- adopt: ↓ negative = anchor adoption decays with distance (plausibility-window prediction)")
    md.append("- df:    ↓ negative = direction-follow decays with distance")
    md.append("- em:    ≈ 0 = exact-match stable across strata (anchor distance does not damage em beyond initial drop)")
    md.append("")
    md.extend(md_blocks)

    md_path.write_text("\n".join(md) + "\n")
    print(f"[wrote] {md_path}")


if __name__ == "__main__":
    main()
